name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Configure
        run: cmake -B build .
      
      - name: Build
        working-directory: build
        run: make
      
      - name: Run Tests
        working-directory: build
        run: make test
